version: '3.8'

services:
  frontend:
    build: ./frontend-app-autorizador
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
